[package]
name = "bbcli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = "4.5.53"
comfy-table = "7.2.1"
config = "0.15.19"
reqwest = "0.12.24"
tokio = "1.48.0"
serde = "1.0.228"
